title: Christopher Landaverde
show_downloads: false
theme: jekyll-theme-minimal
header_pages:
  -projects.md
  -about.md
Navigation:
  - title: Projects
    url: /projects/
  - title: About
    url: /about/
  - title: Blog
    url: /blog/
  - title: Contact
    url: /contact/